<div class="index-page">
    <div class="index-page-logo">
        <img class="img-responsive" src="<?php echo $this->basePath() . '/img/wcm_logo.png' ?>" />
    </div>
    <div class="index-page-welcome">
        <h1>Welcome to Weill Cornell Medical College API!</h1>
        <p>If you have any questions regarding WCMC API application, please <a href="mailto:viy2003@med.cornell.edu">contact administrator</a>.</p>
    </div>
</div>